import 'package:flutter/material.dart';
import 'package:lari_exchange/core/app_theme/advanced_app_theme/advanced_theme_app_colors.dart';
import 'package:lari_exchange/core/app_theme/app_colors.dart';
import 'package:lari_exchange/core/app_theme/minimal_app_theme/minimal_app_colors.dart';
import 'package:lari_exchange/core/app_theme/themedata/helper/app_theme_enum.dart';
import '../basic_app_theme/basic_theme_app_colors.dart';

class AppTheme {
  static List<ThemeData> themes = [
    lightTheme,
    darkTheme,
    minimalLightTheme,
    minimalDarkTheme,
    advancedLightTheme,
    advancedDarkTheme,
    basicLightTheme,
    basicDarkTheme,
  ];

  // === Helper for local Montserrat font ===
  static TextTheme montserratLight = ThemeData.light().textTheme.apply(fontFamily: 'Montserrat');
  static TextTheme montserratDark = ThemeData.dark().textTheme.apply(fontFamily: 'Montserrat');

  /// Default Light Theme
  static ThemeData lightTheme = ThemeData(
    brightness: Brightness.light,
    scaffoldBackgroundColor: LightColors.backgroundColor,
    primaryColor: LightColors.appPrimary,
    colorScheme: ColorScheme.light(
      primary: LightColors.appPrimary,
      surface: LightColors.backgroundColor,
    ),
    textTheme: montserratLight,
    extensions: const <ThemeExtension<dynamic>>[
      AppColors(
        isDarkMode: LightColors.isDarkMode,
        textBlack: LightColors.textBlack,
        black: LightColors.black,
        subTextBlack: LightColors.subTextBlack,
        blackRed: LightColors.blackRed,
        dimBlack: LightColors.dimBlack,
        labelGray: LightColors.labelGray,
        textGray: LightColors.textGray,
        whiteBlue: LightColors.whiteBlue,
        lineGray: LightColors.lineGray,
        bgGray: LightColors.bgGray,
        cardBg: LightColors.cardBg,
        backgroundColorBlack: LightColors.backgroundColorBlack,
        backgroundColor: LightColors.backgroundColor,
        gradientBg: LightColors.gradientBg,
        textPrimary: LightColors.textPrimary,
        lightPrimaryBase: LightColors.lightPrimaryBase,
        appPrimary: LightColors.appPrimary,
        appPrimaryLight: LightColors.appPrimaryLight,
        appPrimaryDark: LightColors.appPrimaryDark,
        appPrimaryDarker: LightColors.appPrimaryDarker,
        lightRed: LightColors.lightRed,
        lightPink: LightColors.lightPink,
        yellow: LightColors.yellow,
        lightGrayPink: LightColors.lightGrayPink,
        lightGreen: LightColors.lightGreen,
        darkerPrimary: LightColors.darkerPrimary,
        appPrimarySecondary: LightColors.appPrimarySecondary,
        darkestPrimary: LightColors.darkestPrimary,
        lightBlue: LightColors.lightBlue,
        errorRed: LightColors.errorRed,
        textSecondary: LightColors.textSecondary,
        appPrimary20: LightColors.appPrimary20,
        sheetBgPrimary: LightColors.sheetBgPrimary,
        lightPrimary: LightColors.lightPrimary,
        bgPrimary: LightColors.bgPrimary,
        white: LightColors.white,
      ),
    ],
  );

  /// Default Dark Theme
  static ThemeData darkTheme = ThemeData(
    brightness: Brightness.dark,
    scaffoldBackgroundColor: DarkColors.backgroundColor,
    primaryColor: DarkColors.appPrimary,
    colorScheme: ColorScheme.dark(
      primary: DarkColors.appPrimary,
      surface: DarkColors.backgroundColor,
    ),
    textTheme: montserratDark,
    extensions: const <ThemeExtension<dynamic>>[
      AppColors(
        isDarkMode: DarkColors.isDarkMode,
        textBlack: DarkColors.textBlack,
        black: DarkColors.black,
        subTextBlack: DarkColors.subTextBlack,
        blackRed: DarkColors.blackRed,
        backgroundColorBlack: DarkColors.backgroundColorBlack,
        dimBlack: DarkColors.dimBlack,
        labelGray: DarkColors.labelGray,
        textGray: DarkColors.textGray,
        whiteBlue: DarkColors.whiteBlue,
        lineGray: DarkColors.lineGray,
        bgGray: DarkColors.bgGray,
        cardBg: DarkColors.cardBg,
        backgroundColor: DarkColors.backgroundColor,
        gradientBg: DarkColors.gradientBg,
        textPrimary: DarkColors.textPrimary,
        lightPrimaryBase: DarkColors.lightPrimaryBase,
        appPrimary: DarkColors.appPrimary,
        appPrimaryLight: DarkColors.appPrimaryLight,
        appPrimaryDark: DarkColors.appPrimaryDark,
        appPrimaryDarker: DarkColors.appPrimaryDarker,
        lightRed: DarkColors.lightRed,
        lightPink: DarkColors.lightPink,
        yellow: DarkColors.yellow,
        lightGrayPink: DarkColors.lightGrayPink,
        lightGreen: DarkColors.lightGreen,
        darkerPrimary: DarkColors.darkerPrimary,
        appPrimarySecondary: DarkColors.appPrimarySecondary,
        darkestPrimary: DarkColors.darkestPrimary,
        lightBlue: DarkColors.lightBlue,
        errorRed: DarkColors.errorRed,
        textSecondary: DarkColors.textSecondary,
        appPrimary20: DarkColors.appPrimary20,
        sheetBgPrimary: DarkColors.sheetBgPrimary,
        lightPrimary: DarkColors.lightPrimary,
        bgPrimary: DarkColors.bgPrimary,
        white: DarkColors.white,
      ),
    ],
  );

  /// Minimal Light Theme
  static ThemeData minimalLightTheme = ThemeData(
    brightness: Brightness.light,
    scaffoldBackgroundColor: MinimalLightColors.appPrimary20,
    primaryColor: MinimalLightColors.appPrimary,
    colorScheme: ColorScheme.light(
      primary: MinimalLightColors.appPrimary,
      surface: MinimalLightColors.appPrimaryLight,
    ),
    textTheme: montserratLight,
    extensions: const <ThemeExtension<dynamic>>[
      AppColors(
        isDarkMode: false,
        textBlack: LightColors.textBlack,
        black: LightColors.black,
        subTextBlack: MinimalLightColors.subTextBlack,
        blackRed: LightColors.lightRed,
        dimBlack: MinimalLightColors.subTextBlack,
        labelGray: MinimalLightColors.bgGray,
        textGray: MinimalLightColors.subTextBlack,
        whiteBlue: MinimalLightColors.appPrimaryLight,
        lineGray: MinimalLightColors.lineGray,
        bgGray: MinimalLightColors.bgGray,
        cardBg: MinimalLightColors.appPrimaryLight,
        backgroundColorBlack: MinimalLightColors.subTextBlack,
        backgroundColor: MinimalLightColors.appPrimary20,
        gradientBg: MinimalLightColors.appPrimaryLight,
        textPrimary: LightColors.textPrimary,
        lightPrimaryBase: MinimalLightColors.appPrimary20,
        appPrimary: MinimalLightColors.appPrimary,
        appPrimaryLight: MinimalLightColors.appPrimaryLight,
        appPrimaryDark: MinimalLightColors.appPrimaryDark,
        appPrimaryDarker: MinimalLightColors.appPrimaryDarker,
        lightRed: LightColors.lightRed,
        lightPink: MinimalLightColors.appPrimaryLight,
        yellow: MinimalLightColors.yellow,
        lightGrayPink: MinimalLightColors.bgGray,
        lightGreen: LightColors.lightGreen,
        darkerPrimary: MinimalLightColors.appPrimaryDark,
        appPrimarySecondary: MinimalLightColors.appPrimarySecondary,
        darkestPrimary: MinimalLightColors.appPrimaryDarker,
        lightBlue: MinimalLightColors.appPrimaryLight,
        errorRed: LightColors.lightRed,
        textSecondary: MinimalLightColors.subTextBlack,
        appPrimary20: MinimalLightColors.appPrimary20,
        sheetBgPrimary: MinimalLightColors.appPrimary20,
        lightPrimary: MinimalLightColors.appPrimaryLight,
        bgPrimary: MinimalLightColors.appPrimary20,
        white: LightColors.white,
      ),
    ],
  );

  /// Minimal Dark Theme
  static ThemeData minimalDarkTheme = ThemeData(
    brightness: Brightness.dark,
    scaffoldBackgroundColor: MinimalDarkColors.appPrimary20,
    primaryColor: MinimalDarkColors.appPrimary,
    colorScheme: ColorScheme.dark(
      primary: MinimalDarkColors.appPrimary,
      surface: MinimalDarkColors.appPrimaryLight,
    ),
    textTheme: montserratDark,
    extensions: const <ThemeExtension<dynamic>>[
      AppColors(
        isDarkMode: true,
        textBlack: DarkColors.textBlack,
        black: DarkColors.black,
        subTextBlack: MinimalDarkColors.subTextBlack,
        blackRed: DarkColors.lightRed,
        dimBlack: MinimalDarkColors.subTextBlack,
        labelGray: MinimalDarkColors.bgGray,
        textGray: MinimalDarkColors.subTextBlack,
        whiteBlue: MinimalDarkColors.appPrimaryLight,
        lineGray: DarkColors.lineGray,
        bgGray: MinimalDarkColors.bgGray,
        cardBg: MinimalDarkColors.appPrimaryLight,
        backgroundColorBlack: MinimalDarkColors.subTextBlack,
        backgroundColor: MinimalDarkColors.appPrimary20,
        gradientBg: MinimalDarkColors.appPrimaryLight,
        textPrimary: MinimalDarkColors.textPrimary,
        lightPrimaryBase: MinimalDarkColors.appPrimary20,
        appPrimary: MinimalDarkColors.appPrimary,
        appPrimaryLight: MinimalDarkColors.appPrimaryLight,
        appPrimaryDark: MinimalDarkColors.appPrimaryDark,
        appPrimaryDarker: MinimalDarkColors.appPrimaryDarker,
        lightRed: DarkColors.lightRed,
        lightPink: MinimalDarkColors.appPrimaryLight,
        yellow: DarkColors.yellow,
        lightGrayPink: DarkColors.bgGray,
        lightGreen: DarkColors.lightGreen,
        darkerPrimary: MinimalDarkColors.appPrimaryDark,
        appPrimarySecondary: MinimalDarkColors.appPrimarySecondary,
        darkestPrimary: MinimalDarkColors.appPrimaryDarker,
        lightBlue: MinimalDarkColors.appPrimaryLight,
        errorRed: DarkColors.lightRed,
        textSecondary: MinimalDarkColors.subTextBlack,
        appPrimary20: MinimalDarkColors.appPrimary20,
        sheetBgPrimary: MinimalDarkColors.appPrimary20,
        lightPrimary: MinimalDarkColors.appPrimaryLight,
        bgPrimary: MinimalDarkColors.appPrimary20,
        white: DarkColors.white,
      ),
    ],
  );

  /// Advanced Light Theme
  static final ThemeData advancedLightTheme = ThemeData(
    brightness: Brightness.light,
    scaffoldBackgroundColor: AdvanceLightColors.backgroundColor,
    primaryColor: AdvanceLightColors.appPrimary,
    colorScheme: ColorScheme.light(
      primary: AdvanceLightColors.appPrimary,
      secondary: AdvanceLightColors.appPrimarySecondary,
      surface: AdvanceLightColors.cardBg,
      background: AdvanceLightColors.backgroundColor,
      onPrimary: AdvanceLightColors.white,
      onSecondary: AdvanceLightColors.white,
      onSurface: AdvanceLightColors.textBlack,
    ),
    textTheme: montserratLight.apply(
      bodyColor: AdvanceLightColors.textBlack,
      displayColor: AdvanceLightColors.textBlack,
    ),
    appBarTheme: AppBarTheme(
      backgroundColor: AdvanceLightColors.appPrimary,
      foregroundColor: AdvanceLightColors.white,
      elevation: 0,
    ),
    cardColor: AdvanceLightColors.cardBg,
    dividerColor: AdvanceLightColors.lineGray,
    bottomSheetTheme: BottomSheetThemeData(
      backgroundColor: AdvanceLightColors.sheetBgPrimary,
    ),
    extensions: const <ThemeExtension<dynamic>>[
      AppColors(
        textGray: LightColors.textGray,
        black: LightColors.black,
        backgroundColorBlack: LightColors.backgroundColorBlack,
        darkerPrimary: LightColors.darkerPrimary,
        darkestPrimary: LightColors.darkestPrimary,
        bgPrimary: LightColors.bgPrimary,
        whiteBlue: LightColors.whiteBlue,
        blackRed: LightColors.blackRed,
        lightPrimaryBase: LightColors.lightPrimaryBase,
        lightBlue: LightColors.lightBlue,
        lightGrayPink: LightColors.lightGrayPink,
        lightGreen: LightColors.lightGreen,
        lightPink: LightColors.lightPink,
        lightPrimary: LightColors.lightPrimary,
        lightRed: LightColors.lightRed,
        textBlack: LightColors.textBlack,
        dimBlack: LightColors.dimBlack,
        labelGray: LightColors.labelGray,
        gradientBg: LightColors.gradientBg,
        isDarkMode: AdvanceLightColors.isDarkMode,
        textPrimary: AdvanceLightColors.textBlack,
        textSecondary: AdvanceLightColors.textSecondary,
        lineGray: AdvanceLightColors.lineGray,
        bgGray: AdvanceLightColors.bgGray,
        cardBg: AdvanceLightColors.cardBg,
        backgroundColor: AdvanceLightColors.backgroundColor,
        sheetBgPrimary: AdvanceLightColors.sheetBgPrimary,
        white: LightColors.white,
        appPrimary: AdvanceLightColors.appPrimary,
        appPrimaryLight: AdvanceLightColors.appPrimaryLight,
        appPrimaryDark: AdvanceLightColors.appPrimaryDark,
        appPrimaryDarker: AdvanceLightColors.appPrimaryDarker,
        appPrimarySecondary: AdvanceLightColors.appPrimarySecondary,
        appPrimary20: AdvanceLightColors.appPrimary20,
        yellow: AdvanceLightColors.yellow,
        errorRed: LightColors.errorRed,
        subTextBlack: LightColors.subTextBlack,
      ),
    ],
  );

  /// Advanced Dark Theme
  static ThemeData advancedDarkTheme = ThemeData(
    brightness: Brightness.dark,
    scaffoldBackgroundColor: AdvanceDarkColors.appPrimary20,
    primaryColor: AdvanceDarkColors.appPrimary,
    colorScheme: ColorScheme.dark(
      primary: AdvanceDarkColors.appPrimary,
      surface: AdvanceDarkColors.appPrimaryLight,
    ),
    textTheme: montserratDark,
    extensions: const <ThemeExtension<dynamic>>[
      AppColors(
        isDarkMode: true,
        textBlack: DarkColors.textBlack,
        black: DarkColors.black,
        subTextBlack: DarkColors.subTextBlack,
        blackRed: DarkColors.lightRed,
        dimBlack: DarkColors.subTextBlack,
        labelGray: DarkColors.bgGray,
        textGray: DarkColors.subTextBlack,
        whiteBlue: AdvanceDarkColors.appPrimaryLight,
        lineGray: DarkColors.lineGray,
        bgGray: DarkColors.bgGray,
        cardBg: AdvanceDarkColors.appPrimaryLight,
        backgroundColorBlack: DarkColors.subTextBlack,
        backgroundColor: AdvanceDarkColors.appPrimary20,
        gradientBg: AdvanceDarkColors.appPrimaryLight,
        textPrimary: DarkColors.textPrimary,
        lightPrimaryBase: AdvanceDarkColors.appPrimary20,
        appPrimary: AdvanceDarkColors.appPrimary,
        appPrimaryLight: AdvanceDarkColors.appPrimaryLight,
        appPrimaryDark: AdvanceDarkColors.appPrimaryDark,
        appPrimaryDarker: AdvanceDarkColors.appPrimaryDarker,
        lightRed: DarkColors.lightRed,
        lightPink: AdvanceDarkColors.appPrimaryLight,
        yellow: DarkColors.yellow,
        lightGrayPink: DarkColors.bgGray,
        lightGreen: DarkColors.lightGreen,
        darkerPrimary: AdvanceDarkColors.appPrimaryDark,
        appPrimarySecondary: AdvanceDarkColors.appPrimarySecondary,
        darkestPrimary: AdvanceDarkColors.appPrimaryDarker,
        lightBlue: AdvanceDarkColors.appPrimaryLight,
        errorRed: DarkColors.lightRed,
        textSecondary: DarkColors.subTextBlack,
        appPrimary20: AdvanceDarkColors.appPrimary20,
        sheetBgPrimary: AdvanceDarkColors.appPrimary20,
        lightPrimary: AdvanceDarkColors.appPrimaryLight,
        bgPrimary: AdvanceDarkColors.appPrimary20,
        white: DarkColors.white,
      ),
    ],
  );

  /// Basic Light Theme
  static final ThemeData basicLightTheme = ThemeData(
    brightness: Brightness.light,
    scaffoldBackgroundColor: BasicLightColors.backgroundColor,
    primaryColor: BasicLightColors.appPrimary,
    colorScheme: ColorScheme.light(
      primary: BasicLightColors.appPrimary,
      secondary: BasicLightColors.appPrimarySecondary,
      surface: BasicLightColors.surfaceDark,
      background: BasicLightColors.backgroundColor,
      onPrimary: BasicLightColors.textPrimary,
      onSecondary: BasicLightColors.textPrimary,
      onSurface: BasicLightColors.textPrimary,
    ),
    textTheme: montserratLight.apply(
      bodyColor: BasicLightColors.textPrimary,
      displayColor: BasicLightColors.textPrimary,
    ),
    appBarTheme: AppBarTheme(
      backgroundColor: BasicLightColors.backgroundColor,
      foregroundColor: BasicLightColors.textPrimary,
      elevation: 0,
    ),
    cardColor: BasicLightColors.cardNavy1,
    dividerColor: BasicLightColors.borderLight,
    bottomSheetTheme: const BottomSheetThemeData(
      backgroundColor: BasicLightColors.backgroundColor,
    ),
    extensions: const <ThemeExtension<dynamic>>[
      AppColors(
        textBlack: LightColors.textBlack,
        black: LightColors.black,
        subTextBlack: DarkColors.subTextBlack,
        isDarkMode: BasicLightColors.isDarkMode,
        textPrimary: BasicLightColors.textPrimary,
        textSecondary: BasicLightColors.textSecondary,
        backgroundColor: BasicLightColors.backgroundColor,
        lightGrayPink: LightColors.lightGrayPink,
        cardBg: BasicLightColors.cardNavy1,
        sheetBgPrimary: BasicLightColors.backgroundColor,
        white: LightColors.white,
        errorRed: LightColors.errorRed,
        appPrimary: BasicLightColors.appPrimary,
        appPrimaryLight: BasicLightColors.appPrimaryLight,
        appPrimaryDark: BasicLightColors.appPrimaryDark,
        appPrimaryDarker: BasicLightColors.appPrimaryDarker,
        appPrimarySecondary: BasicLightColors.appPrimarySecondary,
        appPrimary20: BasicLightColors.surfaceDark,
        lineGray: BasicLightColors.borderLight,
        bgGray: BasicLightColors.surfaceDark,
        gradientBg: BasicLightColors.cardGradient1,
        textGray: BasicLightColors.textMuted,
        lightPrimaryBase: BasicLightColors.appPrimaryLight,
        lightBlue: Colors.lightBlueAccent,
        lightRed: Colors.redAccent,
        lightPink: Colors.pinkAccent,
        lightGreen: Colors.greenAccent,
        lightPrimary: LightColors.lightPrimary,
        bgPrimary: DarkColors.bgPrimary,
        yellow: Colors.amber,
        dimBlack: Colors.black54,
        labelGray: Colors.white54,
        blackRed: Colors.red,
        whiteBlue: Colors.lightBlueAccent,
        darkerPrimary: BasicLightColors.appPrimaryDark,
        darkestPrimary: BasicLightColors.appPrimaryDarker,
        backgroundColorBlack: BasicLightColors.backgroundColor,
      ),
    ],
  );

  /// Basic Dark Theme
  static final ThemeData basicDarkTheme = ThemeData(
    brightness: Brightness.dark,
    scaffoldBackgroundColor: BasicDarkColors.backgroundColor,
    primaryColor: BasicDarkColors.appPrimary,
    colorScheme: ColorScheme.dark(
      primary: BasicDarkColors.appPrimary,
      secondary: BasicDarkColors.appPrimarySecondary,
      surface: BasicDarkColors.surfaceDark,
      background: BasicDarkColors.backgroundColor,
      onPrimary: BasicDarkColors.textPrimary,
      onSecondary: BasicDarkColors.textPrimary,
      onSurface: BasicDarkColors.textPrimary,
    ),
    textTheme: montserratDark.apply(
      bodyColor: BasicDarkColors.textPrimary,
      displayColor: BasicDarkColors.textPrimary,
    ),
    appBarTheme: AppBarTheme(
      backgroundColor: BasicDarkColors.backgroundColor,
      foregroundColor: BasicDarkColors.textPrimary,
      elevation: 0,
    ),
    cardColor: BasicDarkColors.cardNavy1,
    dividerColor: BasicDarkColors.borderLight,
    bottomSheetTheme: const BottomSheetThemeData(
      backgroundColor: BasicDarkColors.backgroundColor,
    ),
    extensions: const <ThemeExtension<dynamic>>[
      AppColors(
        subTextBlack: DarkColors.subTextBlack,
        isDarkMode: BasicDarkColors.isDarkMode,
        textPrimary: BasicDarkColors.textPrimary,
        textSecondary: BasicDarkColors.textSecondary,
        backgroundColor: BasicDarkColors.backgroundColor,
        cardBg: BasicDarkColors.cardNavy1,
        sheetBgPrimary: BasicDarkColors.backgroundColor,
        white: DarkColors.white,
        errorRed: DarkColors.errorRed,
        black: DarkColors.black,
        appPrimary: BasicDarkColors.appPrimary,
        appPrimaryLight: BasicDarkColors.appPrimaryLight,
        appPrimaryDark: BasicDarkColors.appPrimaryDark,
        appPrimaryDarker: BasicDarkColors.appPrimaryDarker,
        appPrimarySecondary: BasicDarkColors.appPrimarySecondary,
        appPrimary20: BasicDarkColors.surfaceDark,
        lineGray: BasicDarkColors.borderLight,
        bgGray: BasicDarkColors.surfaceDark,
        gradientBg: BasicDarkColors.cardGradient1,
        textGray: BasicDarkColors.textMuted,
        lightPrimaryBase: BasicDarkColors.appPrimaryLight,
        lightBlue: Colors.lightBlueAccent,
        lightRed: Colors.redAccent,
        lightPink: Colors.pinkAccent,
        lightGreen: Colors.greenAccent,
        lightPrimary: LightColors.lightPrimary,
        bgPrimary: DarkColors.bgPrimary,
        yellow: Colors.amber,
        dimBlack: Colors.black54,
        labelGray: Colors.white54,
        blackRed: Colors.red,
        whiteBlue: Colors.lightBlueAccent,
        darkerPrimary: BasicDarkColors.appPrimaryDark,
        darkestPrimary: BasicDarkColors.appPrimaryDarker,
        backgroundColorBlack: BasicDarkColors.backgroundColor,
        textBlack: DarkColors.textBlack,
        lightGrayPink: DarkColors.lightGrayPink,
      ),
    ],
  );
}
